
[program:frankenphp]
group=webextradaemons
command=bash -c "frankenphp run --config /etc/frankenphp/Caddyfile --adapter=caddyfile; exit_code=$?; if [ $exit_code -ne 0 ]; then sleep 2; fi; exit $exit_code"
directory=/var/www/html
autostart=false
autorestart=true
startsecs=3 # Must stay up 3 sec, because "sleep 2" in case of fail
startretries=15
stdout_logfile=/var/tmp/logpipe
stdout_logfile_maxbytes=0
redirect_stderr=true
stopasgroup=true
